apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-portfolio-config
  namespace: default
  labels:
    app: devops-portfolio
data:
  ENVIRONMENT: "production"
  APP_NAME: "DevOps Portfolio"
  LOG_LEVEL: "info"
