apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-portfolio
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ogash3103/DevOps_.git
    targetRevision: main
    path: deploy/helm/portfolio

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-portfolio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
